In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
train = pd.read_csv('/Users/alexanderskovorodko/Desktop/MLops2/model/train.csv')
test = pd.read_csv('/Users/alexanderskovorodko/Desktop/MLops2/model/test.csv')
gender_submission = pd.read_csv('/Users/alexanderskovorodko/Desktop/MLops2/model/gender_submission.csv')

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
train.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [5]:
test.isna().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [6]:
print(train.shape, test.shape)

(891, 9) (418, 8)


In [7]:
# # del train['Name']
# del train['Ticket']
# del train['Cabin']
# # del test['Name']
# del test['Ticket']
# del test['Cabin']

In [8]:
train.head()

PassengerId  Survived  Pclass  Sex       Age  SibSp  Parch      Fare  \
0            1         0       3    1  0.271174  0.125    0.0  0.014151   
1            2         1       1    0  0.472229  0.125    0.0  0.139136   
2            3         1       3    0  0.321438  0.000    0.0  0.015469   
3            4         1       1    0  0.434531  0.125    0.0  0.103644   
4            5         0       3    1  0.434531  0.000    0.0  0.015713   

   Embarked  
0         2  
1         0  
2         2  
3         2  
4         2

In [9]:
test.head()

PassengerId  Pclass  Sex       Age  SibSp     Parch      Fare  Embarked
0          892       3    1  0.452723  0.000  0.000000  0.015282         1
1          893       3    0  0.617566  0.125  0.000000  0.013663         2
2          894       2    1  0.815377  0.000  0.000000  0.018909         1
3          895       3    1  0.353818  0.000  0.000000  0.016908         2
4          896       3    0  0.287881  0.125  0.111111  0.023984         2

In [10]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()

In [11]:
def auto_encode(dataset_name, column_name):
    dataset_name[column_name] = LE.fit_transform(dataset_name[column_name])
    print(LE.classes_)
    print(np.sort(dataset_name[column_name].unique()))
    print('')

In [12]:
auto_encode(train, 'Sex')
auto_encode(train, 'Embarked')

auto_encode(test, 'Sex')
auto_encode(test, 'Embarked')

[0 1]
[0 1]

[0 1 2 3]
[0 1 2 3]

[0 1]
[0 1]

[0 1 2]
[0 1 2]



In [13]:
from sklearn.preprocessing import MinMaxScaler 
scaler = MinMaxScaler()

In [14]:
scaling_columns = ['Age', 'SibSp', 'Parch', 'Fare']

In [15]:
train[scaling_columns] = scaler.fit_transform(train[scaling_columns])
test[scaling_columns] = scaler.fit_transform(test[scaling_columns])

In [16]:
train.head()

PassengerId  Survived  Pclass  Sex       Age  SibSp  Parch      Fare  \
0            1         0       3    1  0.271174  0.125    0.0  0.014151   
1            2         1       1    0  0.472229  0.125    0.0  0.139136   
2            3         1       3    0  0.321438  0.000    0.0  0.015469   
3            4         1       1    0  0.434531  0.125    0.0  0.103644   
4            5         0       3    1  0.434531  0.000    0.0  0.015713   

   Embarked  
0         2  
1         0  
2         2  
3         2  
4         2

In [17]:
train['Age'].fillna(int(train['Age'].mean()), inplace=True)
test['Age'].fillna(int(test['Age'].mean()), inplace=True)
test['Fare'].fillna(int(test['Fare'].mean()), inplace=True)

In [18]:
train.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [19]:
test.isna().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [20]:
train.head(10)

PassengerId  Survived  Pclass  Sex       Age  SibSp     Parch      Fare  \
0            1         0       3    1  0.271174  0.125  0.000000  0.014151   
1            2         1       1    0  0.472229  0.125  0.000000  0.139136   
2            3         1       3    0  0.321438  0.000  0.000000  0.015469   
3            4         1       1    0  0.434531  0.125  0.000000  0.103644   
4            5         0       3    1  0.434531  0.000  0.000000  0.015713   
5            6         0       3    1  0.000000  0.000  0.000000  0.016510   
6            7         0       1    1  0.673285  0.000  0.000000  0.101229   
7            8         0       3    1  0.019854  0.375  0.166667  0.041136   
8            9         1       3    0  0.334004  0.000  0.333333  0.021731   
9           10         1       2    0  0.170646  0.125  0.000000  0.058694   

   Embarked  
0         2  
1         0  
2         2  
3         2  
4         2  
5         1  
6         2  
7         2  
8         2  
9         0

In [21]:
# train.to_csv('/Users/alexanderskovorodko/Desktop/MLops2/model/train.csv', index = None, header=True) 
# test.to_csv('/Users/alexanderskovorodko/Desktop/MLops2/model/test.csv', index = None, header=True) 

# Make Machine Learning Model with XGBoost

In [22]:
X = train.drop('Survived', axis=1)
y = train['Survived']

print('Shape of X: ', X.shape)
print('Shape of y: ', y.shape)

Shape of X:  (891, 8)
Shape of y:  (891,)


In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1337)

x_test, x_valid, y_test, y_valid = train_test_split(x_test, y_test, test_size=0.5, random_state=1337)

In [25]:
x_train

PassengerId  Pclass  Sex       Age  SibSp     Parch      Fare  Embarked
647          648       1    1  0.698417  0.000  0.000000  0.069291         0
848          849       2    1  0.346569  0.000  0.166667  0.064412         2
398          399       2    1  0.283740  0.000  0.000000  0.020495         2
787          788       3    1  0.095250  0.500  0.166667  0.056848         1
226          227       2    1  0.233476  0.000  0.000000  0.020495         2
..           ...     ...  ...       ...    ...       ...       ...       ...
167          168       3    0  0.560191  0.125  0.666667  0.054457         2
232          233       2    1  0.736115  0.000  0.000000  0.026350         2
860          861       3    1  0.509927  0.250  0.000000  0.027538         2
189          190       3    1  0.447097  0.000  0.000000  0.015412         2
151          152       1    0  0.271174  0.125  0.000000  0.129995         2

[712 rows x 8 columns]

In [26]:
from xgboost import XGBClassifier

In [27]:
import xgboost as xgb
from sklearn.metrics import accuracy_score
res = []
max_depth = range(1,10)
n_estimators = [50, 100, 150, 200, 250, 300]
learning_rate = [0.01,.05, 0.1, 0.5, 1]
for i in max_depth:
    for n in n_estimators:
        for m in learning_rate:
            gbm = xgb.XGBClassifier(max_depth=i, n_estimators=n, learning_rate=m).fit(x_train,y_train)
            predictions = gbm.predict(x_valid)
            acc_sore = (accuracy_score(y_valid, predictions))   
            res.append((acc_sore, i, n, m))
            print('accuracy:', acc_sore)
            print('learning_rate', m)
            print('n_estimators', n)
            print('max_depth', i)
            print('')
            print()

accuracy: 0.7666666666666667
learning_rate 0.01
n_estimators 50
max_depth 1


accuracy: 0.7666666666666667
learning_rate 0.05
n_estimators 50
max_depth 1


accuracy: 0.7666666666666667
learning_rate 0.1
n_estimators 50
max_depth 1


accuracy: 0.7777777777777778
learning_rate 0.5
n_estimators 50
max_depth 1


accuracy: 0.8
learning_rate 1
n_estimators 50
max_depth 1


accuracy: 0.7666666666666667
learning_rate 0.01
n_estimators 100
max_depth 1


accuracy: 0.7666666666666667
learning_rate 0.05
n_estimators 100
max_depth 1


accuracy: 0.7888888888888889
learning_rate 0.1
n_estimators 100
max_depth 1


accuracy: 0.8222222222222222
learning_rate 0.5
n_estimators 100
max_depth 1


accuracy: 0.7888888888888889
learning_rate 1
n_estimators 100
max_depth 1


accuracy: 0.7666666666666667
learning_rate 0.01
n_estimators 150
max_depth 1


accuracy: 0.8
learning_rate 0.05
n_estimators 150
max_depth 1


accuracy: 0.8
learning_rate 0.1
n_estimators 150
max_depth 1


accuracy: 0.7888888888888889
learn

accuracy: 0.7888888888888889
learning_rate 0.01
n_estimators 250
max_depth 4


accuracy: 0.8
learning_rate 0.05
n_estimators 250
max_depth 4


accuracy: 0.7666666666666667
learning_rate 0.1
n_estimators 250
max_depth 4


accuracy: 0.7666666666666667
learning_rate 0.5
n_estimators 250
max_depth 4


accuracy: 0.7777777777777778
learning_rate 1
n_estimators 250
max_depth 4


accuracy: 0.8
learning_rate 0.01
n_estimators 300
max_depth 4


accuracy: 0.7888888888888889
learning_rate 0.05
n_estimators 300
max_depth 4


accuracy: 0.7555555555555555
learning_rate 0.1
n_estimators 300
max_depth 4


accuracy: 0.7777777777777778
learning_rate 0.5
n_estimators 300
max_depth 4


accuracy: 0.7777777777777778
learning_rate 1
n_estimators 300
max_depth 4


accuracy: 0.8
learning_rate 0.01
n_estimators 50
max_depth 5


accuracy: 0.8111111111111111
learning_rate 0.05
n_estimators 50
max_depth 5


accuracy: 0.8111111111111111
learning_rate 0.1
n_estimators 50
max_depth 5


accuracy: 0.7888888888888889
lea

accuracy: 0.7666666666666667
learning_rate 0.01
n_estimators 150
max_depth 8


accuracy: 0.8
learning_rate 0.05
n_estimators 150
max_depth 8


accuracy: 0.8
learning_rate 0.1
n_estimators 150
max_depth 8


accuracy: 0.7666666666666667
learning_rate 0.5
n_estimators 150
max_depth 8


accuracy: 0.7444444444444445
learning_rate 1
n_estimators 150
max_depth 8


accuracy: 0.7777777777777778
learning_rate 0.01
n_estimators 200
max_depth 8


accuracy: 0.7888888888888889
learning_rate 0.05
n_estimators 200
max_depth 8


accuracy: 0.7888888888888889
learning_rate 0.1
n_estimators 200
max_depth 8


accuracy: 0.7888888888888889
learning_rate 0.5
n_estimators 200
max_depth 8


accuracy: 0.7555555555555555
learning_rate 1
n_estimators 200
max_depth 8


accuracy: 0.7777777777777778
learning_rate 0.01
n_estimators 250
max_depth 8


accuracy: 0.7888888888888889
learning_rate 0.05
n_estimators 250
max_depth 8


accuracy: 0.7888888888888889
learning_rate 0.1
n_estimators 250
max_depth 8


accuracy: 0.77

In [28]:
max(res)

(0.8444444444444444, 3, 150, 0.05)

In [29]:
preds_class = gbm.predict(x_test)
accuracy_score(y_test, preds_class)

0.797752808988764

**XGBRegressor**

In [30]:
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV


params = {'max_depth': range(1,10),
           'n_estimators': [50, 100, 150, 200, 250, 300]}
model = XGBRegressor()

grid = GridSearchCV(estimator=model, 
                   param_grid=params,
                   scoring='r2', 
                   verbose=1)

grid.fit(x_train, y_train)

print("Best parameters:", grid.best_params_)
print("Best Score (R2): ", (grid.best_score_))


Fitting 5 folds for each of 54 candidates, totalling 270 fits
Best parameters: {'max_depth': 2, 'n_estimators': 50}
Best Score (R2):  0.4052823753139263


In [31]:
from sklearn.metrics import mean_squared_error, accuracy_score, r2_score
xgb_tuned = XGBRegressor(**grid.best_params_).fit(x_train, y_train)
y_pred = grid.predict(x_test)
np.sqrt(mean_squared_error(y_test, y_pred))

0.36951484251796746

In [32]:
max(res)

(0.8444444444444444, 3, 150, 0.05)

**RANDOM FOREST**

In [33]:
from sklearn.ensemble import RandomForestClassifier

res = []

min_samples_split = range(2,10)
n_estimators = [50, 100, 150, 200, 250, 300]
min_samples_leaf = range(2,10)

for i in min_samples_split:
    for n in n_estimators:
        for m in min_samples_leaf:
            rf = RandomForestClassifier(criterion='gini', 
                             n_estimators=n,
                             min_samples_split=i,
                             min_samples_leaf=m,
                             max_features='auto',
                             random_state=1,
                             n_jobs=-1)
            rf.fit(x_train, y_train)
            predictions = rf.predict(x_valid)
            acc_sore = (accuracy_score(y_valid, predictions))      
            res.append((acc_sore, i, n, m))
            print('accuracy:', acc_sore)
            print('min_samples_split',i)
            print('n_estimators', n)
            print('min_samples_leaf', m)
            print('')
            print()
            

accuracy: 0.8222222222222222
min_samples_split 2
n_estimators 50
min_samples_leaf 2


accuracy: 0.8333333333333334
min_samples_split 2
n_estimators 50
min_samples_leaf 3


accuracy: 0.8222222222222222
min_samples_split 2
n_estimators 50
min_samples_leaf 4


accuracy: 0.8222222222222222
min_samples_split 2
n_estimators 50
min_samples_leaf 5


accuracy: 0.8111111111111111
min_samples_split 2
n_estimators 50
min_samples_leaf 6


accuracy: 0.8
min_samples_split 2
n_estimators 50
min_samples_leaf 7


accuracy: 0.8
min_samples_split 2
n_estimators 50
min_samples_leaf 8


accuracy: 0.8333333333333334
min_samples_split 2
n_estimators 50
min_samples_leaf 9


accuracy: 0.8111111111111111
min_samples_split 2
n_estimators 100
min_samples_leaf 2


accuracy: 0.8333333333333334
min_samples_split 2
n_estimators 100
min_samples_leaf 3


accuracy: 0.8222222222222222
min_samples_split 2
n_estimators 100
min_samples_leaf 4


accuracy: 0.8222222222222222
min_samples_split 2
n_estimators 100
min_samples_lea

accuracy: 0.8333333333333334
min_samples_split 4
n_estimators 50
min_samples_leaf 3


accuracy: 0.8222222222222222
min_samples_split 4
n_estimators 50
min_samples_leaf 4


accuracy: 0.8222222222222222
min_samples_split 4
n_estimators 50
min_samples_leaf 5


accuracy: 0.8111111111111111
min_samples_split 4
n_estimators 50
min_samples_leaf 6


accuracy: 0.8
min_samples_split 4
n_estimators 50
min_samples_leaf 7


accuracy: 0.8
min_samples_split 4
n_estimators 50
min_samples_leaf 8


accuracy: 0.8333333333333334
min_samples_split 4
n_estimators 50
min_samples_leaf 9


accuracy: 0.8111111111111111
min_samples_split 4
n_estimators 100
min_samples_leaf 2


accuracy: 0.8333333333333334
min_samples_split 4
n_estimators 100
min_samples_leaf 3


accuracy: 0.8222222222222222
min_samples_split 4
n_estimators 100
min_samples_leaf 4


accuracy: 0.8222222222222222
min_samples_split 4
n_estimators 100
min_samples_leaf 5


accuracy: 0.8111111111111111
min_samples_split 4
n_estimators 100
min_samples_le

accuracy: 0.8333333333333334
min_samples_split 6
n_estimators 50
min_samples_leaf 3


accuracy: 0.8222222222222222
min_samples_split 6
n_estimators 50
min_samples_leaf 4


accuracy: 0.8222222222222222
min_samples_split 6
n_estimators 50
min_samples_leaf 5


accuracy: 0.8111111111111111
min_samples_split 6
n_estimators 50
min_samples_leaf 6


accuracy: 0.8
min_samples_split 6
n_estimators 50
min_samples_leaf 7


accuracy: 0.8
min_samples_split 6
n_estimators 50
min_samples_leaf 8


accuracy: 0.8333333333333334
min_samples_split 6
n_estimators 50
min_samples_leaf 9


accuracy: 0.8111111111111111
min_samples_split 6
n_estimators 100
min_samples_leaf 2


accuracy: 0.8333333333333334
min_samples_split 6
n_estimators 100
min_samples_leaf 3


accuracy: 0.8222222222222222
min_samples_split 6
n_estimators 100
min_samples_leaf 4


accuracy: 0.8222222222222222
min_samples_split 6
n_estimators 100
min_samples_leaf 5


accuracy: 0.8111111111111111
min_samples_split 6
n_estimators 100
min_samples_le

accuracy: 0.8
min_samples_split 8
n_estimators 50
min_samples_leaf 3


accuracy: 0.8222222222222222
min_samples_split 8
n_estimators 50
min_samples_leaf 4


accuracy: 0.8222222222222222
min_samples_split 8
n_estimators 50
min_samples_leaf 5


accuracy: 0.8111111111111111
min_samples_split 8
n_estimators 50
min_samples_leaf 6


accuracy: 0.8
min_samples_split 8
n_estimators 50
min_samples_leaf 7


accuracy: 0.8
min_samples_split 8
n_estimators 50
min_samples_leaf 8


accuracy: 0.8333333333333334
min_samples_split 8
n_estimators 50
min_samples_leaf 9


accuracy: 0.8333333333333334
min_samples_split 8
n_estimators 100
min_samples_leaf 2


accuracy: 0.8222222222222222
min_samples_split 8
n_estimators 100
min_samples_leaf 3


accuracy: 0.8222222222222222
min_samples_split 8
n_estimators 100
min_samples_leaf 4


accuracy: 0.8222222222222222
min_samples_split 8
n_estimators 100
min_samples_leaf 5


accuracy: 0.8111111111111111
min_samples_split 8
n_estimators 100
min_samples_leaf 6


accuracy

In [34]:
max(res)

(0.8444444444444444, 8, 200, 2)